/*
 * $Id: dlgEdit.java 29 2014-03-30 04:41:52Z eldon_r $
 *
 * dlgEdit.java
 *
 * Created on 13/11/2011, 4:49:40 PM
 *
 * This dialog is for editing of both new and existing rules.
 * If strTransactionLines is empty (note: null not handled) assumed existing.
 * Otherwise, assumed edit of new rule, and editingRow value is ignored.
 * Upon return (assuming it is called modally) blnCancelModalDialog will show
 * whether or not the edit was OK'd (submitted) or canceled. (very cludgy, FIXME)
 */

package customqif;

/**
 *
 * @author Eldon
 */
public class dlgEdit extends javax.swing.JDialog {

    frmCustomiseQIF parent;
    int rowBeingEdited = -1;
    boolean blnNewTransaction = false;

    /** Creates new form dlgEdit */
    public dlgEdit(frmCustomiseQIF parentForm, boolean modal,
            String strTransactionLines,
            String strNarration,
            String strTransactionType,
            String strReplacement,
            SortedComboBoxModel model,
            int editingRow) {
        super(parentForm, modal);
        initComponents();
        parent=parentForm;
        rowBeingEdited=editingRow;
        parent.blnCancelModalDialog = true;
        if (strTransactionLines.isEmpty()) {
            jpTransaction.setVisible(false);
            setSize(getWidth(), getHeight() - jpTransaction.getHeight());
            blnNewTransaction = false;
        } else {
            jtaTransaction.setText(strTransactionLines);
            blnNewTransaction = true;
        }
        jtfNarration.setText(strNarration);
        jtfTransactionType.setText(strTransactionType);
        jtfAccount.setText(strReplacement);
        jcbAccount.setModel(model);
        if (model.getIndexOf(strReplacement) >= 0) {
            jcbAccount.setSelectedItem(strReplacement);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEdit = new javax.swing.JPanel();
        jpTransaction = new javax.swing.JPanel();
        lblTransaction = new javax.swing.JLabel();
        jspTransaction = new javax.swing.JScrollPane();
        jtaTransaction = new javax.swing.JTextArea();
        jpNarration = new javax.swing.JPanel();
        lblPattern = new javax.swing.JLabel();
        jtfNarration = new javax.swing.JTextField();
        jpTransactionType = new javax.swing.JPanel();
        lblTransactionType = new javax.swing.JLabel();
        jtfTransactionType = new javax.swing.JTextField();
        jpReplacementAccount = new javax.swing.JPanel();
        lblReplacementAccount = new javax.swing.JLabel();
        jcbAccount = new javax.swing.JComboBox();
        lblNewAccount = new javax.swing.JLabel();
        jtfAccount = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Rule Editor");
        setResizable(false);

        lblTransaction.setLabelFor(jspTransaction);
        lblTransaction.setText("Unmatched Record:");

        jtaTransaction.setColumns(20);
        jtaTransaction.setEditable(false);
        jtaTransaction.setRows(5);
        jspTransaction.setViewportView(jtaTransaction);

        javax.swing.GroupLayout jpTransactionLayout = new javax.swing.GroupLayout(jpTransaction);
        jpTransaction.setLayout(jpTransactionLayout);
        jpTransactionLayout.setHorizontalGroup(
            jpTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTransactionLayout.createSequentialGroup()
                .addGroup(jpTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpTransactionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                    .addGroup(jpTransactionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jspTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpTransactionLayout.setVerticalGroup(
            jpTransactionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTransactionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTransaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
        );

        lblPattern.setLabelFor(jtfNarration);
        lblPattern.setText("Pattern for matching the description / narration");

        javax.swing.GroupLayout jpNarrationLayout = new javax.swing.GroupLayout(jpNarration);
        jpNarration.setLayout(jpNarrationLayout);
        jpNarrationLayout.setHorizontalGroup(
            jpNarrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNarrationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpNarrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPattern, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jtfNarration, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpNarrationLayout.setVerticalGroup(
            jpNarrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNarrationLayout.createSequentialGroup()
                .addComponent(lblPattern)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNarration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblTransactionType.setText("Pattern for matching the transaction type (usually leave as default)");

        javax.swing.GroupLayout jpTransactionTypeLayout = new javax.swing.GroupLayout(jpTransactionType);
        jpTransactionType.setLayout(jpTransactionTypeLayout);
        jpTransactionTypeLayout.setHorizontalGroup(
            jpTransactionTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTransactionTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTransactionTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTransactionType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTransactionType, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpTransactionTypeLayout.setVerticalGroup(
            jpTransactionTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTransactionTypeLayout.createSequentialGroup()
                .addComponent(lblTransactionType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblReplacementAccount.setText("Replacement account name (to match a GnuCash account)");

        jcbAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAccountActionPerformed(evt);
            }
        });

        lblNewAccount.setText("Type a new account here if not in the list:");

        javax.swing.GroupLayout jpReplacementAccountLayout = new javax.swing.GroupLayout(jpReplacementAccount);
        jpReplacementAccount.setLayout(jpReplacementAccountLayout);
        jpReplacementAccountLayout.setHorizontalGroup(
            jpReplacementAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReplacementAccountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpReplacementAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbAccount, javax.swing.GroupLayout.Alignment.TRAILING, 0, 454, Short.MAX_VALUE)
                    .addComponent(lblReplacementAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(lblNewAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jtfAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpReplacementAccountLayout.setVerticalGroup(
            jpReplacementAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpReplacementAccountLayout.createSequentialGroup()
                .addComponent(lblReplacementAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNewAccount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnOK.setMnemonic('O');
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setMnemonic('C');
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEditLayout = new javax.swing.GroupLayout(jpEdit);
        jpEdit.setLayout(jpEditLayout);
        jpEditLayout.setHorizontalGroup(
            jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpNarration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpTransactionType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpEditLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addComponent(jpReplacementAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpEditLayout.setVerticalGroup(
            jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditLayout.createSequentialGroup()
                .addComponent(jpTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpNarration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpTransactionType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpReplacementAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        parent.blnCancelModalDialog = true;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (blnNewTransaction) {
            parent.tableModelInProgress.addRow(new Object[]{jtfNarration.getText(), jtfTransactionType.getText(), jtfAccount.getText()});
        } else {
            parent.replaceRow(rowBeingEdited, jtfNarration.getText(), jtfTransactionType.getText(), jtfAccount.getText());
        }
        parent.blnCancelModalDialog = false;
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void jcbAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAccountActionPerformed
        if (evt.getActionCommand().equals("comboBoxChanged")) {
            jtfAccount.setText(jcbAccount.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jcbAccountActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox jcbAccount;
    private javax.swing.JPanel jpEdit;
    private javax.swing.JPanel jpNarration;
    private javax.swing.JPanel jpReplacementAccount;
    private javax.swing.JPanel jpTransaction;
    private javax.swing.JPanel jpTransactionType;
    private javax.swing.JScrollPane jspTransaction;
    private javax.swing.JTextArea jtaTransaction;
    private javax.swing.JTextField jtfAccount;
    private javax.swing.JTextField jtfNarration;
    private javax.swing.JTextField jtfTransactionType;
    private javax.swing.JLabel lblNewAccount;
    private javax.swing.JLabel lblPattern;
    private javax.swing.JLabel lblReplacementAccount;
    private javax.swing.JLabel lblTransaction;
    private javax.swing.JLabel lblTransactionType;
    // End of variables declaration//GEN-END:variables

}
